#!/bin/sh
TMUX= tmux new-session -d 'localhost'
tmux new-window 'Main'
#tmux new-window 'Ranger'
tmux new-window 'Other'

tmux new-session -d 'remote'
tmux new-window 'Pi-hole'
tmux new-window 'QNAP'
tmux new-window 'VPN-1'
tmux new-window 'VPN-2'
tmux new-window 'VPN-3'

tmux -2 attach-session -d
